# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1254, 698)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.combo_monitor_tc = QtWidgets.QComboBox(self.groupBox_2)
        self.combo_monitor_tc.setObjectName("combo_monitor_tc")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_monitor_tc)
        self.combo_controller_tc = QtWidgets.QComboBox(self.groupBox_2)
        self.combo_controller_tc.setObjectName("combo_controller_tc")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_controller_tc)
        self.horizontalLayout_6.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.combo_output_mode = QtWidgets.QComboBox(self.groupBox)
        self.combo_output_mode.setObjectName("combo_output_mode")
        self.horizontalLayout_5.addWidget(self.combo_output_mode)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.line_trim_reading1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.line_trim_reading1.setObjectName("line_trim_reading1")
        self.horizontalLayout_4.addWidget(self.line_trim_reading1)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.line_trime_output1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.line_trime_output1.setObjectName("line_trime_output1")
        self.horizontalLayout_4.addWidget(self.line_trime_output1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line_trim_reading1_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.line_trim_reading1_2.setObjectName("line_trim_reading1_2")
        self.horizontalLayout_3.addWidget(self.line_trim_reading1_2)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.line_trim_output2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.line_trim_output2.setObjectName("line_trim_output2")
        self.horizontalLayout_3.addWidget(self.line_trim_output2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.combo_profile_number = QtWidgets.QComboBox(self.groupBox_3)
        self.combo_profile_number.setObjectName("combo_profile_number")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_profile_number)
        self.combo_profile_tracking = QtWidgets.QComboBox(self.groupBox_3)
        self.combo_profile_tracking.setObjectName("combo_profile_tracking")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_profile_tracking)
        self.horizontalLayout_7.addLayout(self.formLayout_2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 10)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 10)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = LivePlotWidget(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_edit_profile = QtWidgets.QPushButton(Dialog)
        self.btn_edit_profile.setObjectName("btn_edit_profile")
        self.horizontalLayout.addWidget(self.btn_edit_profile)
        self.btn_start_run = QtWidgets.QPushButton(Dialog)
        self.btn_start_run.setObjectName("btn_start_run")
        self.horizontalLayout.addWidget(self.btn_start_run)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 20)
        self.verticalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_2.setTitle(_translate("Dialog", "Temperature Input Setup:"))
        self.label_4.setText(_translate("Dialog", "Monitoring TC Type:"))
        self.label_5.setText(_translate("Dialog", "Process Control TC Type: "))
        self.groupBox.setTitle(_translate("Dialog", "Output 3 Setup:"))
        self.label_3.setText(_translate("Dialog", "Output Mode: "))
        self.groupBox_4.setTitle(_translate("Dialog", "Retransmission Output Trims:"))
        self.label.setText(_translate("Dialog", "-->"))
        self.label_2.setText(_translate("Dialog", "-->"))
        self.groupBox_3.setTitle(_translate("Dialog", "Furnace Profile:"))
        self.label_6.setText(_translate("Dialog", "Select Furnace Profile: "))
        self.label_7.setText(_translate("Dialog", "Profile Tracking Mode: "))
        self.btn_edit_profile.setText(_translate("Dialog", "Edit Profile"))
        self.btn_start_run.setText(_translate("Dialog", "Start Furnace Run"))

from Live_Data_Plotter import LivePlotWidget
